### ISSUE TITLE
Setup kanban board

### ISSUE THREAD

**Issue by binyamolango** [binyamolango/recipe_app2#11]
# Hi Reviewer 👋

- https://github.com/users/binyamolango/projects/3
- we are a group of two.

**Comment by thecodechaser** [comment]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @binyamolango, and @Ochiengsteven👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️

- [ ] None of the task cards have the number of points in the [Xpt] prefix. Please make sure that every task card has the number of points in the [Xpt] prefix as requested in the project requirements. The number indicates the number of points that show how complex the task is. 1 point = 1 hour of estimated work. (Time estimate distributions should be fair)

![image](https://github.com/binyamolango/recipe_app2/assets/83803414/5fdba981-92ef-4f4c-8907-8012ebf5e963)

- [ ] The below task card is missing the description. Please make sure to add a description to the task card as requested in the project requirements that all task cards should have a description.

![image](https://github.com/binyamolango/recipe_app2/assets/83803414/988ee719-80fe-4f7b-8ff1-ea77f1ca8a07)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by skyv26** [comment]
## Hi Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNGRmZWFiMzk2Mjg4MDY3ZmY1ZmYyZjg5NTVhOGQzYmVkNjNlNTdiNSZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights
- N/A

## Required Changes ♻️

- [ ] As per the kanban board setup requirements, team should divide the task equally. I noticed that one of you have 16 pts task and other have only 9 pts task. Which is almost 50% difference in contribution. Kindly divide the task equally so that your individual points difference should not be greater than 1 or 2 points.

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ibizugbe** [comment]
Hi @Team👋🏼👋🏼👋🏼, 

![approved](https://github.com/binyamolango/recipe_app2/assets/64643995/a3335ef0-e371-4b79-8408-016de56e3479)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅✅

- [x] Points are fairly distributed amongst team members👍🏼.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
